# Generated by Django 5.2.7 on 2026-06-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_notification_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendancerecord',
            new_name='attendance__trainee_8d966a_idx',
            old_name='attendance_a_trainee_753a39_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancerecord',
            new_name='attendance__status_17d926_idx',
            old_name='attendance_a_status_606ab5_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='attendance__recipie_2784f5_idx',
            old_name='attendance_n_recipie_c28909_idx',
        ),
        migrations.RenameIndex(
            model_name='session',
            new_name='attendance__date_e758b5_idx',
            old_name='attendance_s_date_58e6ac_idx',
        ),
        migrations.RenameIndex(
            model_name='session',
            new_name='attendance__batch_i_c4a397_idx',
            old_name='attendance_s_batch_i_5a7f20_idx',
        ),
        migrations.AddField(
            model_name='session',
            name='instant_checkin_enabled',
            field=models.BooleanField(default=False, verbose_name='حضور فجائي مفعّل'),
        ),
        migrations.AddField(
            model_name='session',
            name='instant_checkin_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت إرسال الحضور الفجائي'),
        ),
        migrations.AddField(
            model_name='session',
            name='recording_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='رابط المحاضرة المسجلة من التليجرام'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='telegram_channel_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='رابط قناة التليجرام لتسجيلات المحاضرات'),
        ),
    ]
